name: NoBlackSky
version: "1.1.0"
main: it.gamerover.nbs.NBS
description: No black sky in worlds
website: https://www.spigotmc.org/resources/authors/gamerover98.27106/
author: gamerover98
commands:
   NoBlackSky:
     description: No black sky in worlds
     aliases: [nbs]