name: NoBlackSky
version: ${project.version}
main: it.gamerover.nbs.NBS
description: ${project.description}
website: https://www.spigotmc.org/resources/authors/gamerover98.27106/
author: gamerover98
depend: [ProtocolLib]
commands:
   NoBlackSky:
     description: No black sky in worlds
     aliases: [nbs]